### ISSUE TITLE
Weird artifect showing

### ISSUE THREAD

**Issue by jbleuzen** [MoOx/firefox-compact-theme#3]
Hi,
Not sure if it's my firefox configuration or the theme not handling correctly some stuff...

<img width="245" alt="screen shot 2016-04-26 at 07 47 59" src="https://cloud.githubusercontent.com/assets/280681/14808204/ba6ddedc-0b83-11e6-8b7e-101c7ebb4ef3.png">

Looks like the first one is a lock when visiting an HTTPS site and the other one is a bookmark button..
If its a problem with my firefox, would you mind sharing how to hide these ?

**Comment by MoOx** [comment]
Firefox > Tools > Add-ons > Extensions > Beyond Australis > Preferences > Sky Lights > Uncheck Enable Sky Lights.

I will add that in the README

**Comment by jbleuzen** [comment]
So much better, thanks !
